additional_considerations:
  feature_engineering: "Incluy\xF3 la creacion de lag features y el tratamiento de\
    \ variables categoricas con One-Hot Encoding"
  missing_values: Manejado mediante el procesamiento de datos
  scaling: Escalamiento aplicado a las features (Customers, Sales_Lag1)
cross_validation:
  folds: 5
  strategy: K-Fold
description: "Este modelo ha sido seleccionado despu\xE9s de realizar un proceso de\
  \ evaluaci\xF3n, en el cual se optimizaron m\xFAltiples hiperpar\xE1metros utilizando\
  \ b\xFAsqueda aleatoria y validaci\xF3n cruzada. El modelo final demuestra un excelente\
  \ balance entre sesgo y varianza, con un RMSPE consistentemente bajo en los conjuntos\
  \ de datos de validaci\xF3n."
hyperparameters:
  bootstrap: true
  max_depth: 30
  min_samples_leaf: 2
  min_samples_split: 2
  n_estimators: 200
model: Random Forest Regressor
performance:
  feature_importance:
  - Customers
  - Sales_Lag1
  train_RMSPE: 0.0834
  validation_RMSPE: 0.1293
